### ISSUE TITLE
No sleeping allowed bug

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#10]
Players will be stuck on spectator mode when timer goes from 2:00 (start of any round) to 1:40 ish
Need to have it like the spectator function after joining a team where you can spectate then enter again for higher than 20 seconds
Seems like sleeping allowed script is longer than i thought, happens about 1:25 instead of 1:40 so joining late bug is quicker
https://user-images.githubusercontent.com/91396482/179605398-bfa473af-4110-4820-a2c6-8d58b3996a39.mp4

**Comment by upl1nk-v01d** [comment]
Updated responsible thread. Kind of fixed spawning issue.
