### ISSUE TITLE
New error message (I was shooting at a helicopter in bog, probably unrelated. I died to a bot using the new killcam patch, probably related.)

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#13]
![iw3mp 2022-07-18 20-41-49-65](https://user-images.githubusercontent.com/91396482/179604702-6ce6f4c7-d0d3-4c9e-a797-7be547f072fe.jpg)

**Comment by Daxy7** [comment]
Might be a bug in the new killcam script

**Comment by upl1nk-v01d** [comment]
I tested mp_bog map about 2 hours and haven't encountered this error.
Maybe I already fixed it in my new script updates.

**Comment by upl1nk-v01d** [comment]
Yesterday I encountered this by playing map mp_ancient_ultimate at new round start.
I added a patch in thread _player_spawn_loop() in main.gsc to unlink player entity from any other entities, including chopper entity.
