### ISSUE TITLE
Any way to make the pistol animations not slide back autoly when you've depleted your primary weapon? (Video in post)

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#15]
https://user-images.githubusercontent.com/91396482/184539346-638b583f-6487-4407-b084-fa1f1cd9c3e9.mp4

**Comment by upl1nk-v01d** [comment]
I'm afraid only new empty idle xanim can solve this issue.
http://v01d.rf.gd/info/cod4x/beretta.png
About six months ago researched and did succeed to create custom viewmodel with a custom xanim in blender, but exported object animation was very incorrect.
Maybe some day I will resolve this.
