### ISSUE TITLE
What's causing this bug? (Player ragdoll activation is disabled and starts twitching, sometimes more severe)

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#16]
https://user-images.githubusercontent.com/91396482/185229751-d328a6ab-0b2f-44c6-8a04-afd9afe2124e.mp4

It reminds me of when you playback a demo or spectate someone. (It flickers the same way in sudden movements)
https://youtu.be/1sWgWQkik70?t=879

**Comment by upl1nk-v01d** [comment]
bad physics engine.
