### ISSUE TITLE
Solving the xmodel limit when running high object count maps with mods (close this if you've already added it) (linux doesn't have shortcuts so there must be a workaround maybe try adding it in server.cfg. i'll test this)

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#17]
"[cod directory]\cod4x18_dedrun.exe" +set r_xassetnum xmodel=2300 material=4096 image=4000 weapon=170 +exec server.cfg +set fs_game mods/v01d

Edit: it doesn't work even on server.cfg

![it dont 3](https://user-images.githubusercontent.com/91396482/187030287-abcbc30d-25e6-4698-bdd8-dcfdc1051d71.png)

**Comment by upl1nk-v01d** [comment]
good intel!
added to my symlink.
