### ISSUE TITLE
In case you forgot anything, (reduce fall damage dizziness depending on height) (B+3 selection combo deletes hud elements temporarily) (make maprotation randomization more varied)

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#18]

**Comment by upl1nk-v01d** [comment]
When B is presses, the map (left top corner) and kill info (left bottom corner) is hidden and vice versa.
The research is still in progress.

**Comment by upl1nk-v01d** [comment]
I finally solved the minimap dissapearance when pressed B button.
The code was in sdk's hud.menu file.
You can now download my updated mod.ff and z_v01d.iwd from my shared Google Drive! :)
But dizziness issue is wip.

**Comment by upl1nk-v01d** [comment]
Dizziness duration is now based on calculations of damage amount.
