### ISSUE TITLE
 Bug Report: Full ammo at new round but no reserve ammo to reload the weapon

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#2]
This happens when you've used up all of your reserve ammo in one round, and still have that weapon the next round
The reserve ammo comes back the second round after no reserve ammo for 2 rounds

**Comment by upl1nk-v01d** [comment]
Fixed full ammo giving on new round.
Please see https://github.com/upl1nk-v01d/cod4x_v01d_mod/blob/main/scripts/money.gsc line 557.

**Comment by upl1nk-v01d** [comment]
Fixed giving full ammo on buying new weapon.
Please see https://github.com/upl1nk-v01d/cod4x_v01d_mod/blob/main/scripts/money.gsc thread _buy().

**Comment by Daxy7** [comment]
upon depleting all ammo and respawning from new round, script gave me one full clip no reserve ammo (this one not from buying a weapon, buggy on any weapons)

**Comment by Daxy7** [comment]
Closed: Ammo added to buy menu
