### ISSUE TITLE
things broken in cod4 and two errors from cod4x; intel tips, text fade out, cannot correct text easily in IP address box, reloading outside of killcam. Can't find anything on the internet about it.

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#20]
CoD4 1.7  ![2022-09-04 23-54-25-optimized](https://user-images.githubusercontent.com/91396482/188340148-a261df17-4c7c-432b-a613-9562619f19c3.gif) 
CoD4x 18.6 ![2022-09-04 23-55-04-optimized](https://user-images.githubusercontent.com/91396482/188340202-10a7983a-4863-4afd-ba38-7c968fdb6d95.gif)

1.7  ![2022-09-04 23-54-25-3](https://user-images.githubusercontent.com/91396482/188340344-b61f534c-edc0-4457-848a-442fc67a65c7.gif) 
18.6 ![2022-09-04 23-55-04-2](https://user-images.githubusercontent.com/91396482/188340385-1601040d-1354-421d-b622-406cf3f43b89.gif)

Every[?] Version [versions 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6 untested] ![2022-09-05 01-11-14-5-ultra-optimized](https://user-images.githubusercontent.com/91396482/188340688-8ecd620c-0057-48aa-9c20-90d6c68612df.gif)

All[?] Versions
https://user-images.githubusercontent.com/91396482/188476586-37af2990-82e7-4a19-a3fb-56468feeb5c6.mp4
[At least in the last GIF this was patched with killcam cinematics :)]

**Comment by Daxy7** [comment]
Closed temporarily: This may be a problem outside CoD4x's modding range.

**Comment by upl1nk-v01d** [comment]
These errors stands in modding range, so this issue should remain open (ip = menudef issue, ingame text hud = gsc script issue)
v01d is very busy with other things, but in future  v01d will dedicate more time for modding.

**Comment by upl1nk-v01d** [comment]
Well I added my own notify message hud "pulse" transition effect similar to cod4 v1.7 in script code despite cod4x engine hud transition bug. Not sure why are these bugs in cod4x.
I didn't find any solution by replacing sdk hud gsc code with cod4 stock gsc code.
At least bare bones I added in menus.gsc. Next step will be original transition replacement.

**Comment by Daxy7** [comment]
Noticed something strange how this spacing can affect the console too when I open something that has the underscore backspace.

https://user-images.githubusercontent.com/91396482/201004691-5faa6491-ebb5-444d-95a8-00aff028fd61.mp4

It's also in player name,
![ezgif-1-acebf3554b](https://user-images.githubusercontent.com/91396482/201001947-2a687a62-8c3f-4aa0-989e-3973f84e16c3.gif)
key code.
![ezgif-1-04f9a16a0a](https://user-images.githubusercontent.com/91396482/201001954-0eedd402-9e5b-4958-8701-1c809076024c.gif)

**Comment by Daxy7** [comment]
> Well I added my own notify message hud "pulse" transition effect similar to cod4 v1.7 in script code despite cod4x engine hud transition bug. Not sure why are these bugs in cod4x. I didn't find any solution by replacing sdk hud gsc code with cod4 stock gsc code. At least bare bones I added in menus.gsc. Next step will be original transition replacement.

Hmm. Why is it invalid? Maybe a manual cod4x patch would help fix that issue and these bugs.
![notsurwehy](https://user-images.githubusercontent.com/91396482/202441606-8dded680-311a-44d8-9edd-53d1f5054ab7.png)

**Comment by upl1nk-v01d** [comment]
idk why those iwds are invalid. Is those warnings also shows on other mp maps?
inputing player name, keycode and IP favourite reminds me accidentally pressed "Insert" button.
I don't see any issues with inputing r_noclip.

**Comment by upl1nk-v01d** [comment]
That 'Opfor' fading hud element is cod4x (not 1.7) game engine bug.
I made my own hud fx with beautiful cypher fx, but there is a big issue which I cannot overcome which is resulting in ugly text slicing.
I spent about 36 hours for researching this problem and there is no way to increase hud element array limitation size.
I uploaded menus.gsc with improved non-array hud hint message.

**Comment by upl1nk-v01d** [comment]
I also uploaded script files to https://drive.google.com/drive/folders/186GyQw-vKV_bFqAfxdYtRPXcxtaSnoCb?usp=share_link

**Comment by Daxy7** [comment]
resolved: workaround solution

**Comment by Daxy7** [comment]
resolved: workaround solution
