### ISSUE TITLE
New bugs; team imbalance and fully reloading with owned/bought weapons [sample image] 

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#21]
![iw3mp 2022-10-27 19-12-11-57](https://user-images.githubusercontent.com/91396482/198367439-f685c6a9-239c-4819-8d71-74a4b97c0079.jpg)

**Comment by upl1nk-v01d** [comment]
I updated script code issue as you mentioned about bots inbalance.
I added dvar bots_inbalance_feature set to 0 to control/switch off automatic 1 bot adding on loosing team and 1 bot kicking from winning team.
After you buy new weapon you have to buy ammo separately by choosing that weapon again to buy 1 full clip.
You have to load your empty weapon with bought ammo clip before you get into battlefield.

**Comment by upl1nk-v01d** [comment]
Forgot to mention you can add or kick bot by writing in your cod4x dedicaded server's terminal, e.g., "ab axis/allies" or "kb axis/allies".
