### ISSUE TITLE
Disable map rotation randomization because of the chance to replay the same map twice is quite high

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#22]

**Comment by upl1nk-v01d** [comment]
In thread _maps_randomizer() the variable filename has to store an array of defined map names from sv_maps.cfg, which appearently you have not available.
I will make sure that function also checks and gathers map names from original cfg file line or even from ram memory.

**Comment by upl1nk-v01d** [comment]
I'm providing the link to necessary files you can download, including sv_maps.cfg (put this file in cod4x/mods/v01d/ dir).

https://drive.google.com/drive/folders/186GyQw-vKV_bFqAfxdYtRPXcxtaSnoCb?usp=share_link

If this helped, then please close this issue.

**Comment by upl1nk-v01d** [comment]
The dvar 'v01d_maps_randomizer' set by default to 1 is now added in main.gsc.
Now map randomization option can be turned on/off.

**Comment by Daxy7** [comment]
Looks good. Will re-open this if any issues arise/
