### ISSUE TITLE
bug in mod.ff causing grid smoke

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#23]
with mod.ff
![000049](https://user-images.githubusercontent.com/91396482/202114580-0385f3c6-7b16-401c-b571-0de2e0258d6d.jpg)

without mod.ff
![000048](https://user-images.githubusercontent.com/91396482/202114596-024f864d-21ac-4a58-a07e-9e404a9be4c3.jpg)

with mod.ff

https://user-images.githubusercontent.com/91396482/201448157-32e3caca-957f-4d10-9f48-769d643123f2.mp4

without mod.ff

https://user-images.githubusercontent.com/91396482/201448161-653c9159-f8d2-4679-aeca-3188c82c74e5.mp4

**Comment by upl1nk-v01d** [comment]
I'm pretty aware of it.
But there are good news!!
I managed to solve temporary that problem after spending couple of hours deducting it.
I came to conclude that at4_bo_mp and law_mp are causing this, but why idk. But looks like smth about material catch in mod.ff file compilation process.

You can download my updated mod files clicking link down below.
https://drive.google.com/drive/folders/186GyQw-vKV_bFqAfxdYtRPXcxtaSnoCb?usp=sharing

P.S. this issue stays open until this is fixed permanently.

**Comment by upl1nk-v01d** [comment]
You were right about those missing smoke materials!
Looks like I fixed this with placing necessary 12 smoke image files manually from cod4x iwd files in my mod dir!
I don't understand, why those files were missing in compiling process despite those files are readable from compressed stock iwd files.
Please download my updated mod version and give me feedback here after testing my mod.

**Comment by Daxy7** [comment]
fixed: smoke bugs have been resolved
