### ISSUE TITLE
question about the gsc scripts. how do you activate them? all is bad command or cvar

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#24]
![image](https://user-images.githubusercontent.com/91396482/201583180-40fecddb-4f2b-4302-a4da-da3cddb2b3b2.png)

video log of the errors (over 1000)

https://user-images.githubusercontent.com/91396482/201602614-3ddbf630-3981-4d9d-9e36-57a1029206a8.mp4

**Comment by Daxy7** [comment]
Okay, I got some of it working, but the scripts like swaying camera and no HUD aren't there. I'll try fixing the game mode. (g_gametype from dom to sab)



https://user-images.githubusercontent.com/91396482/202120489-dbf0c00e-dce5-454e-bf77-c01a252df407.mp4

**Comment by Daxy7** [comment]
Damn what happened?
![image](https://user-images.githubusercontent.com/91396482/202125830-d1361528-5b8a-4825-8ad6-af2434720705.png)

**Comment by Daxy7** [comment]
It kept adding bots indefinitely
![image](https://user-images.githubusercontent.com/91396482/202126996-1677c4c2-a1ff-42a4-b7f9-5022119d1234.png)

**Comment by Daxy7** [comment]
This Is Epic (I finally got it working by not using z_localserver.bat) (idk why my cpu runs so bad) (I have an i5 3330)


https://user-images.githubusercontent.com/91396482/202140347-5d42e9df-749c-4b97-915e-7a04630ed738.mp4

**Comment by upl1nk-v01d** [comment]
> Okay, I got some of it working, but the scripts like swaying camera and no HUD aren't there. I'll try fixing the game mode. (g_gametype from dom to sab)
> 2022-11-16.07-42-40-2.mp4

You have to set dvar 'set scr_hardcore 1' in your server.cfg file in cod4x mod dir.
I provided updated mod with my server.cfg file with my settings in 
https://drive.google.com/drive/folders/186GyQw-vKV_bFqAfxdYtRPXcxtaSnoCb?usp=share_link

**Comment by upl1nk-v01d** [comment]
> ![image](https://user-images.githubusercontent.com/91396482/201583180-40fecddb-4f2b-4302-a4da-da3cddb2b3b2.png)
> 
> video log of the errors (over 1000)
> 2022-11-14.06-20-51-1.mp4

first of all please download files from my provided Google Drive link with updated mod version and all files from my github repo pressing green button 'CODE' and 'Download ZIP' and extract those github files to your cod4x/mods/v01d/ dir.


https://drive.google.com/drive/folders/186GyQw-vKV_bFqAfxdYtRPXcxtaSnoCb?usp=share_link

![image](https://user-images.githubusercontent.com/56597891/202743102-caefd319-e6b5-4c60-babd-d4fd85da4385.png)


https://github.com/upl1nk-v01d/cod4x_v01d_mod

![image](https://user-images.githubusercontent.com/56597891/202742360-9b4ae846-0edd-4af6-acf3-015310bc876a.png)


in _callbacksetup.gsc file located in cod4x/mods/v01d/maps/mp/gametypes/ folder you have to input this line:
level thread scripts\main::init();


please see the pic below:

![image](https://user-images.githubusercontent.com/56597891/202740884-e1a00615-a288-4ea4-bed1-4456a1a48c79.png)


and set args on your cod4x executable:

![image](https://user-images.githubusercontent.com/56597891/202744449-3f8ec8b2-8bc5-4ac3-944a-3c02e5dc9bcb.png)


At least this is my way to launch cod4x mod successfully.
If this helped, then please close this issue.

**Comment by Daxy7** [comment]
With +exec server.cfg and after following the steps it does this

![image](https://user-images.githubusercontent.com/91396482/202785085-e6a4839b-43d8-4a96-9370-424939e0a4d8.png)

without exec server.cfg i get this

![ezgif-1-b22c2f726a](https://user-images.githubusercontent.com/91396482/202786640-41c91917-97cb-4088-bc2c-3fd6a32036cc.gif)

It only executes half of each mod and fails. How do you have your cod4x_bot_warfare set up?

**Comment by upl1nk-v01d** [comment]
I uploaded my modified bot warfare code to my git repo under maps/mp/bots.
You can test it by deleting your current bot warfare code and replacing by my modified one.

**Comment by Daxy7** [comment]
All of it is working now, but how do you disable the log file or add it? 
![logfileerror](https://user-images.githubusercontent.com/91396482/205346468-8a80c08e-3667-48be-b809-66c07e9448d9.jpg)

**Comment by Daxy7** [comment]
On every other map round, half the scripts randomly don't run again. had to do map_restart to fix it

![image](https://user-images.githubusercontent.com/91396482/206096582-ec941c1f-1f5f-42ed-a744-a643b52f320b.png)

This script runtime error happens every time too after half minute of playing but couldn't see it due to the log file spam errors. I think this bug was occuring on your server too?

**Comment by upl1nk-v01d** [comment]
I added dvars "log_players", "log_motd" and "log_server_con" by default set to 1.
Also you can set by your need in your custom.cfg file by setting to 0 ir any other value to disable.
If you consider to make your own MOTDs, you can simply put "yyyy-mm-dd.log" format text file, e.g., named "2022-12-07.log" file in your  [cod4x]/mods/[yourMod]/motd/ directory and then write your content in it. But then don't forget to set "log_motd" dvar to 1.
Line "self _show_hint_msg(0,"buy ammo choosing weapon",1,1,1,0,1,-200,-70);" is now commented out.
