### ISSUE TITLE
I placed an artillery on mp_pow_rld and the server crashed

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#25]
![iw3mp 2022-12-02 16-14-26-12](https://user-images.githubusercontent.com/91396482/205337203-689942ca-01f9-4d22-9592-f75102ea375a.jpg)

**Comment by upl1nk-v01d** [comment]
fixed by uploading new code.
Actually I didn't upload to github that day, but rather modified on my running server.
