### ISSUE TITLE
suggestion: delete challenge completed messages and sound

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#26]
![iw3mp 2022-12-05 23-28-03-01](https://user-images.githubusercontent.com/91396482/205768070-b399af75-c6fb-49da-b216-b582ed9240df.jpg)

**Comment by Daxy7** [comment]
Also, Add +5 seconds to set scr_game_matchstarttime cuz the map has already started when I join your server

we may need a half, or more divider for weapons since the starting weapon colt pistol goes up to 72 bullets. it is kinda overpowered

**Comment by Daxy7** [comment]
furthermore, a small script for adding or deleting a bot when human players join or leave to make teams balanced.

![image](https://user-images.githubusercontent.com/91396482/206098824-876db8ab-c4e2-428d-b4f3-8953f9e74485.png)

**Comment by Daxy7** [comment]
part of the team on mp_finca keeps jumping at the wall and knifing each other. waypoint issue? way to fix the idling with custom gsc script? 
![iw3mp 2022-12-07 05-33-07-23](https://user-images.githubusercontent.com/91396482/206102924-a188dd82-80f0-447a-b66e-bb60e336c49c.jpg)

**Comment by upl1nk-v01d** [comment]
I added dvar "enable_challenges" condition in _missions.gsc file.
Now you can disable challenges notifications by setting dvar "enable_challenges" to 0 in your custom.cfg file.
For dvar "scr_game_matchstarttime" I will code up a warmup match some time.
The mp_finca and other maps are full with shitty waypoints. I will fix em someday.
