### ISSUE TITLE
new recoil mechanic seems to be too spicy on the bots, (vids included)

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#27]
https://user-images.githubusercontent.com/91396482/205775970-ed94fe36-57cd-4f6e-8192-7c015af20edb.mp4

https://user-images.githubusercontent.com/91396482/205776837-33649225-5ddc-49f2-9215-8b895fe1b936.mp4

**Comment by upl1nk-v01d** [comment]
I added dvar "bots_recoil_spicyness" set to 0.2 by default.
You can add more recoil spicyness by increasing the number.
