### ISSUE TITLE
one bot or more after every round is kicked, resulting in unbalanced teams. there is instant death on an 7-foot fall. height damage script error? i was on mp_harbor_v2 and fell off a ledge.

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#28]
![1boteveryroundkicked](https://user-images.githubusercontent.com/91396482/210104091-c379034b-4d64-44af-bba0-de340d23d29a.jpg)

**Comment by Daxy7** [comment]
plz comment out the mouse acceleration. makes movement feel inconsistent and jerky [tick-based like]

edit: this might be my new corsair mouse causing issues with the game

**Comment by Daxy7** [comment]
also, at the mp_finca map, when in buying intermission, something kicks you out of it. probably a shoddy spawn point since when you spawn you are a little higher than usual and then fall down to normal height. maybe make buying intermission a little less sensitive to movement?

edit: happened on mp_broadcast as well

**Comment by upl1nk-v01d** [comment]
You have to set bots_inbalance_feature to 0 on your server to avoid bots automatic kicking and adding.
Mouse acceleration is now active only on slow motion fx on round ending.
Maybe bot was pushing you out of buyzone.

Sometimes when choosing team on in-game menu the encounter bunch of errors is still present and I am still fighting with 128 weapon asset error.

P.S. G-Sorry about yesterdays overflow, I just accidentally switched off my internet before bed time.

**Comment by Daxy7** [comment]
>  Maybe bot was pushing you out of buyzone.

aren't all players set to not collide with anyone temporarily? is the script delayed too much so that happens at the beginning?

> accidentally switched off my internet 

lol what a coincidence, our internet went down at the same time

**Comment by upl1nk-v01d** [comment]
As requested a temporal restriction to bots to push anybody every round start within 60 seconds level.gracePeriod time.

P.S. yeah, quite strange!

**Comment by upl1nk-v01d** [comment]
I reverted back team selection in-game menu, so no SPAWN button anymore.
I uploaded updated mod.ff and iwd file with fix to weapon assets limitation to the following link:

https://drive.google.com/drive/u/1/folders/186GyQw-vKV_bFqAfxdYtRPXcxtaSnoCb

I had to replace stock weapons instead of adding as new ones.
There were no other workaround but only by replacing. I spent many hours studying and researching to solve this limitation issue.
Seems that r_xassetnum wasn't working. But I have an idea to dig even deeper, at least to know that r_xassetnum argument is or is not passed.

**Comment by Daxy7** [comment]
Yeah, I've been thinking that the weapon value is a false positive and doesn't seem to be in other r_xasset set nodes.

`+set r_xassetnum xmodel=1200`
`+set r_xassetnum xmodel=1200 xanim=3200`
`+set r_xassetnum xmodel=2000 material=4096 image=4000`
`+set r_xassetnum material=2560 xmodel=2048 xanim=3200 image=3000`
`+set r_xassetnum material=6000 xmodel=2000 xanim=3200 image=3000 fx=1000`
`"Can't raise material limit that easy, sorry." — IceNinjaman`

This command-line `+set r_xassetnum xmodel=2300 material=4096 image=4000 weapon=170` is from a Bot Warfare video that has recently been privated or deleted.

It may only be the `xmodel=` value that actually works.

**Comment by Daxy7** [comment]
can the cypher fx sound be replaced with smth less clicky? and also have an outro sound like in this clip
https://www.youtube.com/embed/xreaNqVPv6M

**Comment by upl1nk-v01d** [comment]
now cypher fx should be less loud and annoying.
I uploaded the fix (mod.ff and z_v01d.iwd):
https://drive.google.com/drive/u/1/folders/186GyQw-vKV_bFqAfxdYtRPXcxtaSnoCb
