### ISSUE TITLE
Better solution for bot spawn stuck on each other

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#3]
Make all players be able to walk through players for a short time like 3 or 5 seconds

**Comment by upl1nk-v01d** [comment]
Added no player collision with variable timer arg set.
Please see https://github.com/upl1nk-v01d/cod4x_v01d_mod/blob/main/scripts/main.gsc thread _player_collision(timer).

**Comment by Daxy7** [comment]
Bots are dying at spawn with the new patch. Can this be commented out?

**Comment by upl1nk-v01d** [comment]
Even without player collision? 
I had suspicions that bots are cutting each other even with patch. 
Not sure commenting out will do better.

**Comment by Daxy7** [comment]
By the second round and continuing the randomizer timer is too low or stops. Can't go through the bots

**Comment by Daxy7** [comment]
I was talking about the bots dying sometimes at the start of rounds, not player collision

**Comment by upl1nk-v01d** [comment]
in thread _player_collision(timer) commented out level waittill("prematch_over");
on second and nth round it was waiting on notify and not allowing any bypass.

while (isDefined(level.inPrematchPeriod) && level.inPrematchPeriod==true){ wait 1; } is added in case waiting for prematch period to end.
