### ISSUE TITLE
From pastebin - 75alpha - mod.ff extract at the end of the page.dat

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#4]
ERROR: Could not open 'rumble/assault_fire_h.rmb'
ERROR: Could not open 'rumble/assault_fire_l.rmb'
ERROR: Could not open 'rumble/defaultweapon_melee_h.rmb'
ERROR: Could not open 'rumble/defaultweapon_melee_l.rmb'
ERROR: Could not open 'rumble/shotgun_fire_h.rmb'
ERROR: Could not open 'rumble/shotgun_fire_l.rmb'
ERROR: failed loading 'rumble/assault_fire_h.rmb' of type 'rawfile'
ERROR: failed loading 'rumble/assault_fire_l.rmb' of type 'rawfile'
ERROR: failed loading 'rumble/defaultweapon_melee_h.rmb' of type 'rawfile'
ERROR: failed loading 'rumble/defaultweapon_melee_l.rmb' of type 'rawfile'
ERROR: failed loading 'rumble/shotgun_fire_h.rmb' of type 'rawfile'
ERROR: failed loading 'rumble/shotgun_fire_l.rmb' of type 'rawfile'
ERROR: image 'images/ak47_flares.iwi' is missing
ERROR: image 'images/bg_back.iwi' is missing
ERROR: image 'images/bg_blur_back.iwi' is missing
ERROR: image 'images/bg_fogscroll.iwi' is missing
ERROR: image 'images/bg_fogscrollthin.iwi' is missing
ERROR: image 'images/bg_front2.iwi' is missing
ERROR: image 'images/bg_front.iwi' is missing
ERROR: image 'images/button_highlight_end.iwi' is missing
ERROR: image 'images/compass_map_default.iwi' is missing
ERROR: image 'images/compassping_enemyfiring.iwi' is missing
ERROR: image 'images/compassping_green_hollow_mp.iwi' is missing
ERROR: image 'images/compassping_player.iwi' is missing
ERROR: image 'images/dirtchunks.iwi' is missing
ERROR: image 'images/distortion_heat.iwi' is missing
ERROR: image 'images/distortion_ring.iwi' is missing
ERROR: image 'images/exp_igc.iwi' is missing
ERROR: image 'images/exp_spark.iwi' is missing
ERROR: image 'images/explosion_flash_atlas.iwi' is missing
ERROR: image 'images/fire_ball_atlas.iwi' is missing
ERROR: image 'images/fire_patch_ember_add.iwi' is missing
ERROR: image 'images/fire_roar_pm_atlas.iwi' is missing
ERROR: image 'images/flechette_reticle.iwi' is missing
ERROR: image 'images/fx_shell_col.iwi' is missing
ERROR: image 'images/fx_shotgun_shell_col.iwi' is missing
ERROR: image 'images/glow_hs.iwi' is missing
ERROR: image 'images/glow_org.iwi' is missing
ERROR: image 'images/gradient_bottom.iwi' is missing
ERROR: image 'images/gradient_fadein.iwi' is missing
ERROR: image 'images/gradient_top.iwi' is missing
ERROR: image 'images/grass_piece1.iwi' is missing
ERROR: image 'images/hud_40mmgrenade.iwi' is missing
ERROR: image 'images/hud_at4.iwi' is missing
ERROR: image 'images/hud_barrett50cal.iwi' is missing
ERROR: image 'images/hud_desert_eagle.iwi' is missing
ERROR: image 'images/hud_m40a3.iwi' is missing
ERROR: image 'images/lightning.iwi' is missing
ERROR: image 'images/lightning_atlas.iwi' is missing
ERROR: image 'images/line_horizontal.iwi' is missing
ERROR: image 'images/m14_scope_lens_col.iwi' is missing
ERROR: image 'images/m16_flares.iwi' is missing
ERROR: image 'images/mtl_weapon_m40a3_col.iwi' is missing
ERROR: image 'images/mtl_weapon_m40a3_scope_col.iwi' is missing
ERROR: image 'images/objective_line.iwi' is missing
ERROR: image 'images/scope_overlay_m40a3_1024#0.iwi' is missing
ERROR: image 'images/side_small.iwi' is missing
ERROR: image 'images/smk_white_atlas.iwi' is missing
ERROR: image 'images/spark_atlas.iwi' is missing
ERROR: image 'images/spotlight_lensflare.iwi' is missing
ERROR: image 'images/starburst_1p.iwi' is missing
ERROR: image 'images/viewhands_marine_gloves_col.iwi' is missing
ERROR: image 'images/weapon_bullet_col.iwi' is missing
ERROR: image 'images/weapon_m82_col.iwi' is missing
ERROR: image 'images/weapon_m82_scope_col.iwi' is missing
ERROR: image 'images/weapon_m82_scope_lens_col.iwi' is missing
ERROR: image 'images/weapon_parbolic_knife_col.iwi' is missing
ERROR: image 'images/weapon_red_scope_col.iwi' is missing
ERROR: image 'images/weapon_rpg7_col.iwi' is missing
ERROR: image 'images/whisp_spiral.iwi' is missing
ERROR: image 'images/\~weapon_acog_alpha_spc-rgb&we\~29bfeeda.iwi' is missing
ERROR: image 'images/\~weapon_acog_lens_spc-rgb&wea\~a5d30b6d.iwi' is missing
ERROR: image 'images/\~weapon_acog_spc-r-25g-25b-25\~ffe3f99d.iwi' is missing
ERROR: image 'images/\~weapon_at4_spec-rgb&weapon_a\~ec6a4c9a.iwi' is missing
ERROR: Sound file 'sound/weapons/aw_em1/wpn_em1_fire.wav' not found

**Comment by upl1nk-v01d** [comment]
well, I have new task list :D

**Comment by Daxy7** [comment]
For missing images like images/ak47_flares.iwi, go to /mods/v01d/z_v01d.iwd/images/ and rename, replace with transparent iwi file.
Same with sounds. mods/v01d/z_v01d.iwd/sound/weapons/ and rename, replace with blank 0.1-second wav file
Here are templates for both.
Transparent 4×4 res (perhaps a conversion is needed to iwi format. Idk how low CoD4 supports texture resolutions, so it's doubled until 256)
Blank.wav
[Replacing missing files.zip](https://github.com/upl1nk-v01d/cod4x_v01d_mod/files/9426208/Replacing.missing.files.zip)

Not sure how to replace rmb file types.

**Comment by Daxy7** [comment]
Edit: The 0.0 wav file was too old or empty and spammed errors in the console. So, here's one from a 2021 codec.

[Replacing.missing.files.2.zip](https://github.com/upl1nk-v01d/cod4x_v01d_mod/files/9543581/Replacing.missing.files.2.zip)

**Comment by Daxy7** [comment]
[mod-extract data.txt](https://github.com/upl1nk-v01d/cod4x_v01d_mod/files/10031439/mod-extract.data.txt)
There are new lines here about last_stand.wav error not found. Why does it say that? Is it normal? Why not just replace that file with a nothingburger 0.1 second blank wav file instead?
