### ISSUE TITLE
Change -=V01d=- join button to join -=sabotage=- on mod's main menu screen

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#5]

**Comment by upl1nk-v01d** [comment]
you're right! 
In future my vision to create new gamemodes.
I modified that menudef.

**Comment by Daxy7** [comment]
Closed: all main menu buttons styled to v01d's server name.
Comparison:
-=V01d=- -> -=sabotage=-
Join Game -> -=other servers=-
Start New Server -> -=create server=-
Select Profile -> -=select profile=-
Create a Class -> ~~Create a Class~~
Rank & Challenges -> ~~Rank & Challenges~~
Controls -> -=controls=-
Options -> -=options=-
Mods -> ~~Mods~~
Single Player -> ~~Single Player~~
Quit -> -=retire=-
