### ISSUE TITLE
Randomized Maps

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#7]
Can you add the rest of the maps to the random rotation? (shipment3, countdown)
perhaps to include more stock maps (broadcast, cargoship, strike, bloc, crash, vacant)

**Comment by upl1nk-v01d** [comment]
added some stock maps and in cfg file now is set:
set sv_randomMapRotation 0 // 0 = sv_mapRotation is randomized, 1 = sequential order of sv_mapRotation

**Comment by upl1nk-v01d** [comment]
added true maps randomizer.
see _maps_randomizer() thread in main.gsc

**Comment by Daxy7** [comment]
Closed with unknown status/condition
