### ISSUE TITLE
One map unplayable for players

### ISSUE THREAD

**Issue by Daxy7** [upl1nk-v01d/cod4x_v01d_mod#8]
Encountered a very long hitch on mp_efa_lake today (Server connection timed out)
![iw3mp 2022-07-13 21-36-49-28](https://user-images.githubusercontent.com/91396482/179600850-3d7fd483-dacb-4d24-9737-c9c4a695e425.jpg)
After few minutes of playing on the map

**Comment by upl1nk-v01d** [comment]
I have made some adjustments in thread _init_bot_dvars() in main.gsc.
The reason of server hitching was incorrectly set bot_manage_fill after new map loaded.
